import type { TravelerForumReply, TravelerForumThread } from "@rpmf/core";
import { anonymous, seedProvenance } from "./helpers.js";

/**
 * Founding seed wave (v0.1): eighteen short threads and twenty floors. The
 * ten curated runtime notes cite these thread ids, so they stay verbatim.
 */
export const seedThreads: TravelerForumThread[] = [
  {
    id: "tf-ancient-china-000001",
    schemaVersion: 1,
    worldPack: "ancient-china",
    node: "official",
    title: "县库第三天空了，先查什么？",
    postType: "blood-and-tears",
    author: anonymous("anonymous-047"),
    body: "别一看见‘库空’就先抓人。我上局就是这么把自己送走的。先问：账面余额多少，实物多少，多少已经被划作别用，多少只是欠收，钥匙和出入记录分别在谁手里。五个问题没问完之前，‘贪墨’两个字先咽回去。",
    appliesTo: { identities: ["local-official", "emperor", "regent-powerful-minister"], capabilities: ["ledger-evidence-crosscheck"], situations: ["empty-treasury", "suspect-ledgers"] },
    reliability: "corroborated",
    reviewStatus: "approved-for-display",
    provenance: seedProvenance,
    replies: ["tf-reply-000001-01", "tf-reply-000001-02"],
    createdAt: "2026-09-04",
    updatedAt: "2026-09-04",
    archiveTime: "王朝档案"
  },
  {
    id: "tf-ancient-china-000002",
    schemaVersion: 1,
    worldPack: "ancient-china",
    node: "official",
    title: "‘全县都在骂’通常等于你只听见了最响的那拨人",
    postType: "verified-practice",
    author: anonymous("anonymous-203"),
    body: "茶馆、书院、码头、军营、灾棚、宗族祠堂，说的是六种不同的‘民声’。别把一处声音抄成全县支持率。尤其是沉默的人，可能是不在乎，也可能是不敢说。",
    appliesTo: { identities: ["local-official", "scholar", "merchant", "emperor"], capabilities: ["plural-stakeholder-signals"], situations: ["public-reaction", "policy-resistance"] },
    reliability: "corroborated",
    reviewStatus: "approved-for-display",
    provenance: seedProvenance,
    replies: ["tf-reply-000002-01"],
    createdAt: "2026-09-04",
    updatedAt: "2026-09-04",
    archiveTime: "王朝档案"
  },
  {
    id: "tf-ancient-china-000003",
    schemaVersion: 1,
    worldPack: "ancient-china",
    node: "military",
    title: "以后再让我看见‘号称二十万大军’我就杀人",
    postType: "blood-and-tears",
    author: anonymous("anonymous-088"),
    body: "先给我算每天吃多少粮。再算多少人在册、多少能到、多少能打、多少会听命、马还能走几天、欠饷几个月。号称二十万不是一个数字，是六七个数字穿了一件大衣。",
    appliesTo: { identities: ["general", "emperor", "regent-powerful-minister"], capabilities: ["readiness-logistics"], situations: ["military-mobilization", "campaign-planning"] },
    reliability: "corroborated",
    reviewStatus: "approved-for-display",
    provenance: seedProvenance,
    replies: ["tf-reply-000003-01"],
    createdAt: "2026-09-04",
    updatedAt: "2026-09-04",
    archiveTime: "王朝档案"
  },
  {
    id: "tf-ancient-china-000004",
    schemaVersion: 1,
    worldPack: "ancient-china",
    node: "military",
    title: "粮道不是一条路，是一串会翻脸的人",
    postType: "case-report",
    author: anonymous("anonymous-311"),
    body: "地图上路线通，不代表粮到得了。车夫愿不愿走、驿站有没有牲口、地方官肯不肯配合、沿路有没有人截留、天气会不会让一段路直接失效，这些都属于粮道。上局我输在地图太漂亮。",
    appliesTo: { identities: ["general", "local-official", "merchant"], capabilities: ["readiness-logistics", "multiplex-relationship-graph"], situations: ["supply-route", "campaign-planning"] },
    reliability: "plausible",
    reviewStatus: "approved-for-display",
    provenance: seedProvenance,
    replies: ["tf-reply-000004-01"],
    createdAt: "2026-09-04",
    updatedAt: "2026-09-04",
    archiveTime: "王朝档案"
  },
  {
    id: "tf-ancient-china-000005",
    schemaVersion: 1,
    worldPack: "ancient-china",
    node: "survival",
    title: "你知道真相，不代表你有资格说真相",
    postType: "blood-and-tears",
    author: anonymous("anonymous-019"),
    body: "低权限开局最先判断的不是‘我要怎么揭露’，而是‘谁知道我知道、谁会因为我知道而受损、我说了以后谁能保护我’。真相不会替你挡板子。",
    appliesTo: { identities: ["servant", "commoner", "scholar"], capabilities: ["claim-action-consistency", "multiplex-relationship-graph", "curated-practitioner-knowledge"], situations: ["dangerous-knowledge", "whistleblowing"] },
    reliability: "corroborated",
    reviewStatus: "approved-for-display",
    provenance: seedProvenance,
    replies: ["tf-reply-000005-01", "tf-reply-000005-02"],
    createdAt: "2026-09-04",
    updatedAt: "2026-09-04",
    archiveTime: "王朝档案"
  },
  {
    id: "tf-ancient-china-000006",
    schemaVersion: 1,
    worldPack: "ancient-china",
    node: "meta",
    title: "别给奴婢开‘改革全国税制’任务",
    postType: "maintainer-argument",
    author: anonymous("maintainer-109"),
    body: "出生版曾经把能力模块和行政权限捆在一起，导致低权限角色也会收到离谱建议。维护组已把身份权限和 capability 拆开。先活过今晚，再谈一条鞭法。",
    appliesTo: { identities: ["servant", "commoner"], capabilities: ["curated-practitioner-knowledge"], situations: ["permission-mismatch", "overpowered-advice"] },
    reliability: "corroborated",
    reviewStatus: "approved-for-display",
    provenance: seedProvenance,
    replies: ["tf-reply-000006-01"],
    createdAt: "2026-09-04",
    updatedAt: "2026-09-04",
    archiveTime: "王朝档案"
  },
  {
    id: "tf-ancient-china-000007",
    schemaVersion: 1,
    worldPack: "ancient-china",
    node: "household",
    title: "主家突然换钥匙，不一定是在防你",
    postType: "correction",
    author: anonymous("anonymous-126"),
    body: "行为变化可以当信号，不能当动机结论。换钥匙可能是防盗、换库管、丢过东西，也可能真是在收紧你能接触的区域。先找能区分这些解释的下一条证据。",
    appliesTo: { identities: ["servant", "commoner"], capabilities: ["claim-action-consistency"], situations: ["behavior-change", "access-restriction"] },
    reliability: "corroborated",
    reviewStatus: "approved-for-display",
    provenance: seedProvenance,
    replies: ["tf-reply-000007-01"],
    createdAt: "2026-09-04",
    updatedAt: "2026-09-04",
    archiveTime: "王朝档案"
  },
  {
    id: "tf-ancient-china-000008",
    schemaVersion: 1,
    worldPack: "ancient-china",
    node: "emperor",
    title: "奏报都说丰收，粮价为什么涨？",
    postType: "question",
    author: anonymous("anonymous-501"),
    body: "别急着选‘奏报是假’或者‘市场在炒’。先把年份、地区、口径、运输、仓储、征收、灾情和可上市余粮放在一张表上。丰收和粮价上涨并不逻辑互斥。",
    appliesTo: { identities: ["emperor", "regent-powerful-minister", "local-official", "merchant"], capabilities: ["ledger-evidence-crosscheck"], situations: ["price-anomaly", "conflicting-reports"] },
    reliability: "corroborated",
    reviewStatus: "approved-for-display",
    provenance: seedProvenance,
    replies: ["tf-reply-000008-01"],
    createdAt: "2026-09-04",
    updatedAt: "2026-09-04",
    archiveTime: "王朝档案"
  },
  {
    id: "tf-ancient-china-000009",
    schemaVersion: 1,
    worldPack: "ancient-china",
    node: "emperor",
    title: "一道诏书从御前走到县里，已经不是原来那道诏书了",
    postType: "verified-practice",
    author: anonymous("anonymous-344"),
    body: "查政策不要只看‘发没发令’，要看谁转发、谁解释、谁出钱、谁验收、谁承担失败。每经过一层，原目标都有可能被改写成更容易交差的指标。",
    appliesTo: { identities: ["emperor", "regent-powerful-minister", "local-official"], capabilities: ["accountability-execution"], situations: ["policy-execution", "implementation-gap"] },
    reliability: "corroborated",
    reviewStatus: "approved-for-display",
    provenance: seedProvenance,
    replies: ["tf-reply-000009-01"],
    createdAt: "2026-09-04",
    updatedAt: "2026-09-04",
    archiveTime: "王朝档案"
  },
  {
    id: "tf-ancient-china-000010",
    schemaVersion: 1,
    worldPack: "ancient-china",
    node: "emperor",
    title: "老师、母族、内臣都说‘为你好’，先别急着选谁是真心",
    postType: "case-report",
    author: anonymous("anonymous-072"),
    body: "储君开局最危险的图不是‘忠奸图’，是关系类型混在一起。教育依赖、血缘、官职、未来押注、私人恩怨可能同时存在。先画边，再谈阵营。",
    appliesTo: { identities: ["heir"], capabilities: ["multiplex-relationship-graph", "claim-action-consistency"], situations: ["succession-politics", "competing-advisers"] },
    reliability: "plausible",
    reviewStatus: "approved-for-display",
    provenance: seedProvenance,
    replies: ["tf-reply-000010-01"],
    createdAt: "2026-09-04",
    updatedAt: "2026-09-04",
    archiveTime: "王朝档案"
  },
  {
    id: "tf-ancient-china-000011",
    schemaVersion: 1,
    worldPack: "ancient-china",
    node: "emperor",
    title: "三道命令都‘执行完毕’，事情为什么完全没动？",
    postType: "blood-and-tears",
    author: anonymous("anonymous-255"),
    body: "因为‘已行文’、‘已登记’、‘已派人’都可以叫执行。给每个任务写一个外部可观察的验收条件，不然你收到的永远是漂亮动词。",
    appliesTo: { identities: ["regent-powerful-minister", "emperor", "local-official"], capabilities: ["accountability-execution"], situations: ["paper-compliance", "implementation-gap"] },
    reliability: "corroborated",
    reviewStatus: "approved-for-display",
    provenance: seedProvenance,
    replies: ["tf-reply-000011-01"],
    createdAt: "2026-09-04",
    updatedAt: "2026-09-04",
    archiveTime: "王朝档案"
  },
  {
    id: "tf-ancient-china-000012",
    schemaVersion: 1,
    worldPack: "ancient-china",
    node: "merchant",
    title: "便宜货源最贵的部分通常没写在报价里",
    postType: "verified-practice",
    author: anonymous("anonymous-418"),
    body: "商路上比较价格要把损耗、路税、押运、等待、坏账、季节和政治风险都折进去。只看进价，会把一条不稳定路线误认成暴利。",
    appliesTo: { identities: ["merchant"], capabilities: ["ledger-evidence-crosscheck", "readiness-logistics"], situations: ["trade-route", "price-comparison"] },
    reliability: "corroborated",
    reviewStatus: "approved-for-display",
    provenance: seedProvenance,
    replies: ["tf-reply-000012-01"],
    createdAt: "2026-09-04",
    updatedAt: "2026-09-04",
    archiveTime: "王朝档案"
  },
  {
    id: "tf-ancient-china-000013",
    schemaVersion: 1,
    worldPack: "ancient-china",
    node: "merchant",
    title: "谁欠你钱，和谁怕你倒闭，是两张不同的图",
    postType: "verified-practice",
    author: anonymous("anonymous-407"),
    body: "债权关系不等于利益同盟。有人欠你钱却希望你死，有人一文钱不欠却靠你的货路活。商人开局也别把一张账本当成整张关系网。",
    appliesTo: { identities: ["merchant"], capabilities: ["multiplex-relationship-graph"], situations: ["credit-network", "commercial-alliance"] },
    reliability: "plausible",
    reviewStatus: "approved-for-display",
    provenance: seedProvenance,
    replies: ["tf-reply-000013-01"],
    createdAt: "2026-09-04",
    updatedAt: "2026-09-04",
    archiveTime: "王朝档案"
  },
  {
    id: "tf-ancient-china-000014",
    schemaVersion: 1,
    worldPack: "ancient-china",
    node: "arts",
    title: "满城都在骂，不等于天下都在骂",
    postType: "correction",
    author: anonymous("anonymous-166"),
    body: "士人的信息优势也有盲区：你认识的人可能比你想象中更像你。书院里的共识、同年的共识、城市里的共识，最多先当作对应群体的信号。",
    appliesTo: { identities: ["scholar", "heir", "local-official"], capabilities: ["plural-stakeholder-signals"], situations: ["elite-opinion", "public-reaction"] },
    reliability: "corroborated",
    reviewStatus: "approved-for-display",
    provenance: seedProvenance,
    replies: ["tf-reply-000014-01"],
    createdAt: "2026-09-04",
    updatedAt: "2026-09-04",
    archiveTime: "王朝档案"
  },
  {
    id: "tf-ancient-china-000015",
    schemaVersion: 1,
    worldPack: "ancient-china",
    node: "ordinary",
    title: "灾年第一件事不是把家里塞满粮",
    postType: "blood-and-tears",
    author: anonymous("anonymous-021"),
    body: "先问你有几天现金、几天吃的、谁需要药、谁能出门、哪条路还能走、欠谁钱、谁可能来借。全换成粮有时候会让你第二周连药和路费都没了。",
    appliesTo: { identities: ["commoner", "servant", "merchant"], capabilities: ["curated-practitioner-knowledge"], situations: ["famine", "household-crisis"] },
    reliability: "plausible",
    reviewStatus: "approved-for-display",
    provenance: seedProvenance,
    replies: ["tf-reply-000015-01"],
    createdAt: "2026-09-04",
    updatedAt: "2026-09-04",
    archiveTime: "王朝档案"
  },
  {
    id: "tf-ancient-china-000016",
    schemaVersion: 1,
    worldPack: "ancient-china",
    node: "meta",
    title: "血泪帖不是圣旨",
    postType: "maintainer-argument",
    author: anonymous("maintainer-112"),
    body: "论坛原帖保留语气、失败、偏见和争论；只有经过审校的 curated note 才能自动进入 Runtime。帖子越好笑，不代表可靠度越高。",
    appliesTo: { identities: [], capabilities: ["curated-practitioner-knowledge"], situations: ["forum-meta"] },
    reliability: "corroborated",
    reviewStatus: "approved-for-display",
    provenance: seedProvenance,
    replies: ["tf-reply-000016-01"],
    createdAt: "2026-09-04",
    updatedAt: "2026-09-04",
    archiveTime: "王朝档案"
  },
  {
    id: "tf-ancient-china-000017",
    schemaVersion: 1,
    worldPack: "ancient-china",
    node: "survival",
    title: "【封存】穿夜行衣翻墙进户部，效率最高",
    postType: "unverified-trick",
    author: anonymous("anonymous-404"),
    body: "据说比走流程快。",
    appliesTo: { identities: ["servant", "commoner", "scholar", "merchant"], capabilities: ["ledger-evidence-crosscheck"], situations: ["need-central-records"] },
    reliability: "deprecated",
    reviewStatus: "superseded",
    provenance: seedProvenance,
    replies: ["tf-reply-000017-01"],
    createdAt: "2026-09-04",
    updatedAt: "2026-09-04",
    archiveTime: "王朝档案"
  },
  {
    id: "tf-ancient-china-000018",
    schemaVersion: 1,
    worldPack: "ancient-china",
    node: "survival",
    title: "先问：谁会因为你知道这件事而杀你？",
    postType: "verified-practice",
    author: anonymous("anonymous-112"),
    body: "这是低权限信息判断的第一道风险门，不是让你疑神疑鬼。列出受损者、知情者、保护者、你暴露知识的渠道，再决定要不要继续查。",
    appliesTo: { identities: ["servant", "commoner", "scholar", "merchant"], capabilities: ["multiplex-relationship-graph", "red-team"], situations: ["dangerous-knowledge", "investigation-risk"] },
    reliability: "corroborated",
    reviewStatus: "approved-for-display",
    provenance: seedProvenance,
    replies: ["tf-reply-000018-01"],
    createdAt: "2026-09-04",
    updatedAt: "2026-09-04",
    archiveTime: "王朝档案"
  }
];

export const seedReplies: TravelerForumReply[] = [
  { id: "tf-reply-000001-01", threadId: "tf-ancient-china-000001", parentReplyId: null, replyType: "correction", author: anonymous("anonymous-112"), body: "补一句：账面空、实物空、不可支用，是三种不同的‘空’。", reliability: "corroborated", reviewStatus: "approved-for-display", archiveTime: "同一档案期" },
  { id: "tf-reply-000001-02", threadId: "tf-ancient-china-000001", parentReplyId: null, replyType: "case-report", author: anonymous("anonymous-088"), body: "我还遇过仓里真有粮，但已经发霉到不能算可用库存。", reliability: "anecdotal", reviewStatus: "approved-for-display", archiveTime: "同一档案期" },
  { id: "tf-reply-000002-01", threadId: "tf-ancient-china-000002", parentReplyId: null, replyType: "correction", author: anonymous("anonymous-166"), body: "以及别把‘没听见骂声’自动翻译成支持。", reliability: "corroborated", reviewStatus: "approved-for-display", archiveTime: "同一档案期" },
  { id: "tf-reply-000003-01", threadId: "tf-ancient-china-000003", parentReplyId: null, replyType: "maintainer-argument", author: anonymous("maintainer-109"), body: "此句已收录为烽燧图长期精神污染源。技术翻译：名义资源必须与可用、有效资源分栏。", reliability: "corroborated", reviewStatus: "approved-for-display", archiveTime: "同一档案期" },
  { id: "tf-reply-000004-01", threadId: "tf-ancient-china-000004", parentReplyId: null, replyType: "case-report", author: anonymous("anonymous-418"), body: "商路同理。能走，不等于值得走，也不等于下个月还能走。", reliability: "plausible", reviewStatus: "approved-for-display", archiveTime: "同一档案期" },
  { id: "tf-reply-000005-01", threadId: "tf-ancient-china-000005", parentReplyId: null, replyType: "verified-practice", author: anonymous("anonymous-112"), body: "先确认‘谁会因为你知道这件事而杀你’。", reliability: "corroborated", reviewStatus: "approved-for-display", archiveTime: "同一档案期" },
  { id: "tf-reply-000005-02", threadId: "tf-ancient-china-000005", parentReplyId: null, replyType: "correction", author: anonymous("anonymous-126"), body: "也别默认一定有人要杀你。风险门是拿来列可能性和保护路径，不是制造被害妄想。", reliability: "corroborated", reviewStatus: "approved-for-display", archiveTime: "同一档案期" },
  { id: "tf-reply-000006-01", threadId: "tf-ancient-china-000006", parentReplyId: null, replyType: "maintainer-argument", author: anonymous("maintainer-110"), body: "维护记录翻译：不是所有老乡都能调户部的账。", reliability: "corroborated", reviewStatus: "approved-for-display", archiveTime: "同一档案期" },
  { id: "tf-reply-000008-01", threadId: "tf-ancient-china-000008", parentReplyId: null, replyType: "verified-practice", author: anonymous("anonymous-418"), body: "如果能拿到不同市场、不同时间点的价格，比只看一个京城数字强很多。", reliability: "plausible", reviewStatus: "approved-for-display", archiveTime: "同一档案期" },
  { id: "tf-reply-000009-01", threadId: "tf-ancient-china-000009", parentReplyId: null, replyType: "correction", author: anonymous("anonymous-255"), body: "最可怕的是每层都能证明自己完成了流程，最后没人能证明目标实现了。", reliability: "corroborated", reviewStatus: "approved-for-display", archiveTime: "同一档案期" },
  { id: "tf-reply-000010-01", threadId: "tf-ancient-china-000010", parentReplyId: null, replyType: "correction", author: anonymous("anonymous-344"), body: "而且同一个人可以在教育上支持你、在继承问题上防你。别给人贴永久忠诚分。", reliability: "plausible", reviewStatus: "approved-for-display", archiveTime: "同一档案期" },
  { id: "tf-reply-000012-01", threadId: "tf-ancient-china-000012", parentReplyId: null, replyType: "case-report", author: anonymous("anonymous-407"), body: "我那局最便宜的路线，最后贵在等了二十一天。时间也得进账。", reliability: "anecdotal", reviewStatus: "approved-for-display", archiveTime: "同一档案期" },
  { id: "tf-reply-000015-01", threadId: "tf-ancient-china-000015", parentReplyId: null, replyType: "correction", author: anonymous("anonymous-021b"), body: "适用边界提醒：如果已经断市封城，现金价值会快速变化，不能机械照搬。", reliability: "plausible", reviewStatus: "approved-for-display", archiveTime: "同一档案期" },
  { id: "tf-reply-000017-01", threadId: "tf-ancient-china-000017", parentReplyId: null, replyType: "maintainer-argument", author: anonymous("maintainer-110"), body: "封存理由：越权、不可泛化、死亡率不可接受，而且最重要的是你根本没有户部地图。", reliability: "corroborated", reviewStatus: "approved-for-display", archiveTime: "同一档案期" },
  { id: "tf-reply-000007-01", threadId: "tf-ancient-china-000007", parentReplyId: null, replyType: "correction", author: anonymous("anonymous-019"), body: "补：先看换的是哪几把。只换库房不换后院，和全换一遍，是两种信号。", reliability: "plausible", reviewStatus: "approved-for-display", archiveTime: "同一档案期" },
  { id: "tf-reply-000011-01", threadId: "tf-ancient-china-000011", parentReplyId: null, replyType: "case-report", author: anonymous("anonymous-344"), body: "我那局‘已派人’派的是个告了病假的人。验收条件写成‘某日某人到某处画押’以后，才发现派的是个空。", reliability: "anecdotal", reviewStatus: "approved-for-display", archiveTime: "同一档案期" },
  { id: "tf-reply-000013-01", threadId: "tf-ancient-china-000013", parentReplyId: null, replyType: "question", author: anonymous("anonymous-418"), body: "那靠我货路活的人，算盟友还是算风险？他随时可以换一条货路。", reliability: "unknown", reviewStatus: "approved-for-display", archiveTime: "同一档案期" },
  { id: "tf-reply-000014-01", threadId: "tf-ancient-china-000014", parentReplyId: null, replyType: "case-report", author: anonymous("anonymous-203"), body: "反过来也成立：京城不骂，不等于州县不骂。奏报和邸报走的是同一批人的嘴。", reliability: "plausible", reviewStatus: "approved-for-display", archiveTime: "同一档案期" },
  { id: "tf-reply-000016-01", threadId: "tf-ancient-china-000016", parentReplyId: null, replyType: "maintainer-argument", author: anonymous("maintainer-109"), body: "补充：展示层可以引用原帖原句，但引用不等于注入。Runtime 只拿经过审校的 curated note。", reliability: "corroborated", reviewStatus: "approved-for-display", archiveTime: "同一档案期" },
  { id: "tf-reply-000018-01", threadId: "tf-ancient-china-000018", parentReplyId: null, replyType: "correction", author: anonymous("anonymous-126"), body: "第三栏‘保护者’常常是空的。空着也要列出来，别为了好看填一个不可靠的名字。", reliability: "corroborated", reviewStatus: "approved-for-display", archiveTime: "同一档案期" }
];
